final Map<String, String> currenciesDataMap = {
  'BRL': 'Brazilian Real',
  'USD': 'American Dollar',
  'EUR': 'Euro',
  'GBP': 'Libra Esterlina',
  'AUD': 'Australian Dollar',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss franc',
  'JPY': 'Japanese Iene',
  'CNY': 'Chinese Yuan',
  'MXN': 'Maxican Peso',
  'ARS': 'Argentine Peso',
  'INR': 'Indian rupee',
  'ZAR': 'South-African Rand',
  'SEK': 'Swedish krona',
  'NOK': 'Norwegian krone',
  'DKK': 'Danish Krone',
  'NZD': 'New Zealand Dollar',
  'HKD': 'Hong Kong Dollar',
  'SGD': 'Singapura Dollar',
  'KRW': 'South Korean Won',
  'TRY': 'Turkish Lira',
  'RUB': 'Russian ruble',
  'SAR': 'Saudi Riyal',
  'MYR': 'Malaysian Ringgit',
  'THB': 'Thai Baht',
  'IDR': 'Indonesian rupiah',
  'PKR': 'Pakistani Rupee',
  'EGP': 'Egyptian Pound',
  'VND': 'Vietnamese Dong',
  'ILS': 'Israeli Shekel',
  'BHD': 'Bahraini Dinar',
  'KWD': 'Kuwaiti Dinar',
  'LKR': 'Sri Lankan rupee',
  'PEN': 'Peru The Sol',
  'COP': 'colombian peso',
};
